# Generated by Django 5.2.17 on 2026-09-12 23:57

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('product_type', models.CharField(choices=[('single', 'Individual product'), ('bundle', 'Bundle'), ('limited_edition', 'Limited edition'), ('collaboration', 'Collaboration edition')], default='single', max_length=32)),
                ('collaboration_label', models.CharField(blank=True, help_text="Optional edition label shown near the product name, e.g. 'Collaboration edition'. Partner naming/logos are managed in Site settings.", max_length=120)),
                ('short_description', models.CharField(max_length=300)),
                ('description', wagtail.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price shown struck-through when higher than the price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('dimensions_note', models.CharField(blank=True, help_text="e.g. 'Approximately three stacked phones.'", max_length=200)),
                ('materials', models.TextField(blank=True)),
                ('shipping_information', wagtail.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0)),
                ('icon', models.CharField(choices=[('mirror', 'LED mirror'), ('touch', 'Touch control'), ('drawers', 'Drawers'), ('leather', 'Premium finish'), ('travel', 'Travel'), ('size', 'Compact size'), ('crown', 'Crown'), ('sparkle', 'Sparkle')], default='sparkle', max_length=32)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0)),
                ('alt_text', models.CharField(blank=True, help_text="Overrides the image's default alt text.", max_length=255)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0)),
                ('number', models.PositiveSmallIntegerField(default=1, help_text='Displayed as LAYER 01, 02…')),
                ('name', models.CharField(help_text="e.g. 'Lips & Essentials'", max_length=80)),
                ('title', models.CharField(blank=True, help_text='Editorial headline for the layer.', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('contents', models.TextField(blank=True, help_text='One item per line, e.g. Lipsticks / Glosses / Brushes.')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0)),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=200)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
