# Generated by Django 5.2.17 on 2026-09-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('estimated_min_days', models.PositiveSmallIntegerField(default=2)),
                ('estimated_max_days', models.PositiveSmallIntegerField(default=5)),
                ('countries', models.CharField(blank=True, help_text='Comma-separated ISO country codes this method serves. Empty = worldwide.', max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
